site_name: Лабораторная работа
site_description: Публикация статического сайта с использованием MkDocs и CI/CD
site_url: https://zaharenkoliza.github.io/mkdocs-lab/

theme:
  name: mkdocs
  language: ru

nav:
  - Главная: index.md
  - О работе: about.md
  - Инструменты: tools.md

use_directory_urls: true

plugins:
  - search